# Generated by Django 5.1.7 on 2025-03-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_autor_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='biografía',
            new_name='biografia',
        ),
    ]
