# Generated by Django 5.1.7 on 2025-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_editorial_created_by_alter_autor_premios'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma_en',
            field=models.CharField(blank=True, choices=[('ES', 'Español'), ('EN', 'Ingles')], default='ES', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma_es',
            field=models.CharField(blank=True, choices=[('ES', 'Español'), ('EN', 'Ingles')], default='ES', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
