# Generated by Django 5.1.7 on 2025-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_libro_descripcion_en_libro_descripcion_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='is_out_stock',
            field=models.BooleanField(default=False, verbose_name='Está fuera de stock'),
        ),
    ]
