# Generated by Django 5.1.7 on 2025-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_libro_is_out_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='nivel',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=10),
        ),
    ]
