# Generated by Django 5.1.7 on 2025-04-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_editorial_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='nivel',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=10, verbose_name='Nivel'),
        ),
    ]
